apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: dhcpd
  name: dhcpd
spec:
  ports:
  - name: rest
    port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: dhcpd
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: dhcpd
  name: dhcpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oka
      app.kubernetes.io/component: dhcpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oka
        app.kubernetes.io/component: dhcpd
        app.kubernetes.io/version: {{ .Chart.Version }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics" 
    spec:
      hostNetwork: true
      containers:
      - image: imschuler/oka-dhcpd:{{ .Chart.Version }}
        imagePullPolicy: Always
        name: dhcpd
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
            - NET_RAW
            - DAC_OVERRIDE
        ports:
        - containerPort: 67
          hostPort: 67
          protocol: UDP
        - containerPort: 8081
          protocol: TCP
