apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: httpd
  name: httpd
spec:
  ports:
  - name: rest
    port: 8080
    protocol: TCP
    targetPort: 8083
  selector:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: httpd
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: httpd
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oka
      app.kubernetes.io/component: httpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oka
        app.kubernetes.io/component: httpd
        app.kubernetes.io/version: {{ .Chart.Version }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: imschuler/oka-httpd:{{ .Chart.Version }}
        imagePullPolicy: Always
        name: httpd
        ports:
        - containerPort: 8083
          protocol: TCP
