apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: isosd
  name: isosd
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 84
  - name: rest
    port: 8080
    protocol: TCP
    targetPort: 8084
  selector:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: isosd
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: isosd
  name: isosd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oka
      app.kubernetes.io/component: isosd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oka
        app.kubernetes.io/component: isosd
        app.kubernetes.io/version: {{ .Chart.Version }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
        prometheus.io/path: "/metrics"
    spec:
      volumes:
      - name: isos
        hostPath:
           path: /srv/isos
           type: Directory
      - name: dev 
        hostPath:
           path: /dev
           type: Directory
      containers:
      - image: imschuler/oka-isosd:{{ .Chart.Version }}
        imagePullPolicy: Always
        name: isosd
        securityContext:
          privileged: true
        ports:
        - containerPort: 84
          protocol: TCP
        - containerPort: 8084
          protocol: TCP
        volumeMounts:
        - name: isos
          mountPath: /srv/isos
          readOnly: true
        - name: dev 
          mountPath: /dev
