apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: tftpd
  name: tftpd
spec:
  ports:
  - name: rest
    port: 8080
    protocol: TCP
    targetPort: 8082
  selector:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: tftpd
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: oka
    app.kubernetes.io/component: tftpd
  name: tftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oka
      app.kubernetes.io/component: tftpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oka
        app.kubernetes.io/component: tftpd
        app.kubernetes.io/version: {{ .Chart.Version }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: imschuler/oka-tftpd:{{ .Chart.Version }}
        imagePullPolicy: Always
        name: tftpd
        ports:
        - containerPort: 8082
          protocol: TCP
        - containerPort: 69
          protocol: UDP
