apiVersion: v1
kind: ConfigMap
metadata:
  name: hosts
  labels:
    app.kubernetes.io/name: oka
data:
  {{- range .Values.hosts }}
    {{ .host }}: |-
      host:          {{ .host }}
      locale:        {{ .locale }}
      {{- if .disk }}
      disks:
        - {{ .disk }}
      {{- end }}
      {{- if .swraid }}
      disks:    {{- range .swraid }}
                - {{ quote . }}
                {{- end }}
      {{- end }}
      hostname:      {{ .hostname }}
      timezone:      {{ .timezone }}
      {{- if .pxe }}
      pxe:
        ip:          {{ .pxe.ip }}
        mac:         {{ .pxe.mac | lower }}
      {{- end }}
      inet:
        mac:         {{ .inet.mac | lower }}
      {{- if .inet.ip }}
        ip:          {{ .inet.ip }}
        dns:         {{ .inet.dns }}
        gateway:     {{ .inet.gateway }}
      {{- end }}
      {{- if .irmc }}
      irmc:
        ip:          {{ .irmc.ip }}
        user:        {{ .irmc.user }}
        password:    {{ .irmc.password }}
      {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-hosts
  labels:
    app.kubernetes.io/name: oka
data:
  {{ range .Values.hosts }}
    {{ .host }}: |-
      127.0.0.1  localhost
      {{- if and (.pxe) (.pxe.ip) }}
      {{ .pxe.ip }}  {{ .host }}
      {{- else }}
      {{ .inet.ip }} {{ .host }}
      {{- end }}
  {{ end }}
