---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.16
  ansible_runner:
    package_pip: ansible-runner
  python_interpreter:
    package_system: "python312"
    python_path: "/usr/bin/python3.12"
  galaxy:
    collections:
      - name: ansible.posix
      - name: community.general
      - name: ansible.netcommon
  python:
    - pyghmi
    - netaddr
    - jmespath

images:
  base_image:
    name: registry.redhat.io/ubi9/ubi:9.6-1751445649

additional_build_files:
   - src: depot/*
     dest: depot

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install --upgrade pip

  append_final:
    - COPY ./_build/depot /depot

options:
  container_init:
    entrypoint: '[ "/bin/bash", "-c", "ansible-playbook -vv step_${JOB_COMPLETION_INDEX}.yml" ]'
  workdir: /depot
  user: root
