{{ $namespace := .Release.Namespace }}
{{ $subnetns := .Values.subnetns }}
{{- if not (lookup "v1" "ConfigMap" $namespace "hosts") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hosts
  labels:
    app.kubernetes.io/name: oka
immutable: true
data:
  {{- range $key, $value := (lookup "v1" "ConfigMap" $subnetns "hosts").data }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
{{- if not (lookup "v1" "ConfigMap" $namespace "etc-hosts") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-hosts
  labels:
    app.kubernetes.io/name: oka
immutable: true
data:
  {{- range $key, $value := (lookup "v1" "ConfigMap" $subnetns "etc-hosts").data }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
